---
name: Fetch V2Ray CI logs
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: tinuous-inception
      - name: Checkout con/tinuous
        uses: actions/checkout@v4
        with:
          repository: con/tinuous
          path: tinuous
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.8
      - name: Install tinuous dependencies
        run: |
          python -m pip install --upgrade pip wheel internetarchive
          python -m pip install ./tinuous
      - name: Create Data Dir
        run: |
          mkdir data
        working-directory: tinuous-inception
      - name: Run tinuous
        run: tinuous -c ./../fetchV2Ray.yaml --env /dev/null fetch
        working-directory: tinuous-inception/data
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CUSTOM_TOKEN }}
      - name: Copy Secret
        env:
          IA_CONFIG: ${{ secrets.IA_CONFIG }}
        run: |
          mkdir -p $HOME/.config/internetarchive
          echo "$IA_CONFIG"|base64 -d > $HOME/.config/internetarchive/ia.ini
      - name: Upload To Internet Archive
        working-directory: tinuous-inception/data
        run: |
          ia upload --keep-directories --no-derive --checksum --verify --retries=655360  v2ray-action-archive-hqfi0pb *
